//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionLematizador
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reconocimiento", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class Reconocimiento : object
    {
        
        private string FormaCanonicaField;
        
        private int FrecuenciaField;
        
        private int IdFlexionField;
        
        private int IdFormaCanonicaField;
        
        private string PrefijosField;
        
        private string PronombresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonica
        {
            get
            {
                return this.FormaCanonicaField;
            }
            set
            {
                this.FormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica
        {
            get
            {
                return this.IdFormaCanonicaField;
            }
            set
            {
                this.IdFormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijos
        {
            get
            {
                return this.PrefijosField;
            }
            set
            {
                this.PrefijosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pronombres
        {
            get
            {
                return this.PronombresField;
            }
            set
            {
                this.PronombresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCanonica", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoCanonica : object
    {
        
        private int AntiguaField;
        
        private int DRAEXXIIIField;
        
        private string FormaCanonicaField;
        
        private int FrecuenciaField;
        
        private int IdCategoriaField;
        
        private int IdCategoriaGNField;
        
        private int IdFlexionField;
        
        private int MaxAcepcionesField;
        
        private int MaxEtimologiaField;
        
        private int NumAcepcionField;
        
        private int NumAcepcionSecField;
        
        private int NumEtimologiaField;
        
        private int PosAcepcionField;
        
        private int PosAcepcionSecField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Antigua
        {
            get
            {
                return this.AntiguaField;
            }
            set
            {
                this.AntiguaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DRAEXXIII
        {
            get
            {
                return this.DRAEXXIIIField;
            }
            set
            {
                this.DRAEXXIIIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonica
        {
            get
            {
                return this.FormaCanonicaField;
            }
            set
            {
                this.FormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaGN
        {
            get
            {
                return this.IdCategoriaGNField;
            }
            set
            {
                this.IdCategoriaGNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxAcepciones
        {
            get
            {
                return this.MaxAcepcionesField;
            }
            set
            {
                this.MaxAcepcionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxEtimologia
        {
            get
            {
                return this.MaxEtimologiaField;
            }
            set
            {
                this.MaxEtimologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumAcepcion
        {
            get
            {
                return this.NumAcepcionField;
            }
            set
            {
                this.NumAcepcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumAcepcionSec
        {
            get
            {
                return this.NumAcepcionSecField;
            }
            set
            {
                this.NumAcepcionSecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEtimologia
        {
            get
            {
                return this.NumEtimologiaField;
            }
            set
            {
                this.NumEtimologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosAcepcion
        {
            get
            {
                return this.PosAcepcionField;
            }
            set
            {
                this.PosAcepcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosAcepcionSec
        {
            get
            {
                return this.PosAcepcionSecField;
            }
            set
            {
                this.PosAcepcionSecField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPalabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoPalabra : object
    {
        
        private int FrecuenciaField;
        
        private int IdFlexionField;
        
        private int IdFormaCanonicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica
        {
            get
            {
                return this.IdFormaCanonicaField;
            }
            set
            {
                this.IdFormaCanonicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFlexionador", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoFlexionador : object
    {
        
        private int IdFlexionField;
        
        private string PalabraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra
        {
            get
            {
                return this.PalabraField;
            }
            set
            {
                this.PalabraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVerbo", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoVerbo : object
    {
        
        private int FrecuenciaField;
        
        private int IdFlexionField;
        
        private int IdFormaCanonicaField;
        
        private string InfinitivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica
        {
            get
            {
                return this.IdFormaCanonicaField;
            }
            set
            {
                this.IdFormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Infinitivo
        {
            get
            {
                return this.InfinitivoField;
            }
            set
            {
                this.InfinitivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPrimitiva", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoPrimitiva : object
    {
        
        private int IdCategoriaField;
        
        private int IdCategoriaPadreField;
        
        private int IdFamiliaField;
        
        private int IdPrefijoField;
        
        private int IdSufijoField;
        
        private string PadreField;
        
        private string PrefijoField;
        
        private bool ReglaPrefijalField;
        
        private bool ReglaSufijalField;
        
        private string SufijoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaPadre
        {
            get
            {
                return this.IdCategoriaPadreField;
            }
            set
            {
                this.IdCategoriaPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFamilia
        {
            get
            {
                return this.IdFamiliaField;
            }
            set
            {
                this.IdFamiliaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrefijo
        {
            get
            {
                return this.IdPrefijoField;
            }
            set
            {
                this.IdPrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSufijo
        {
            get
            {
                return this.IdSufijoField;
            }
            set
            {
                this.IdSufijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Padre
        {
            get
            {
                return this.PadreField;
            }
            set
            {
                this.PadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo
        {
            get
            {
                return this.PrefijoField;
            }
            set
            {
                this.PrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReglaPrefijal
        {
            get
            {
                return this.ReglaPrefijalField;
            }
            set
            {
                this.ReglaPrefijalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReglaSufijal
        {
            get
            {
                return this.ReglaSufijalField;
            }
            set
            {
                this.ReglaSufijalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sufijo
        {
            get
            {
                return this.SufijoField;
            }
            set
            {
                this.SufijoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPrefijo", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoPrefijo : object
    {
        
        private int CorteField;
        
        private string EtimologiaField;
        
        private string PrefijoField;
        
        private string PrefijoCanonicoField;
        
        private string SignificadoField;
        
        private string SilabacionField;
        
        private string TipoPrefijoField;
        
        private string VariantesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Corte
        {
            get
            {
                return this.CorteField;
            }
            set
            {
                this.CorteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etimologia
        {
            get
            {
                return this.EtimologiaField;
            }
            set
            {
                this.EtimologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo
        {
            get
            {
                return this.PrefijoField;
            }
            set
            {
                this.PrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrefijoCanonico
        {
            get
            {
                return this.PrefijoCanonicoField;
            }
            set
            {
                this.PrefijoCanonicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Significado
        {
            get
            {
                return this.SignificadoField;
            }
            set
            {
                this.SignificadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Silabacion
        {
            get
            {
                return this.SilabacionField;
            }
            set
            {
                this.SilabacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPrefijo
        {
            get
            {
                return this.TipoPrefijoField;
            }
            set
            {
                this.TipoPrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variantes
        {
            get
            {
                return this.VariantesField;
            }
            set
            {
                this.VariantesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFlexion", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoFlexion : object
    {
        
        private string FlexionAbrevEnField;
        
        private string FlexionAbrevEsField;
        
        private string FlexionEnField;
        
        private string FlexionEsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionAbrevEn
        {
            get
            {
                return this.FlexionAbrevEnField;
            }
            set
            {
                this.FlexionAbrevEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionAbrevEs
        {
            get
            {
                return this.FlexionAbrevEsField;
            }
            set
            {
                this.FlexionAbrevEsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionEn
        {
            get
            {
                return this.FlexionEnField;
            }
            set
            {
                this.FlexionEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionEs
        {
            get
            {
                return this.FlexionEsField;
            }
            set
            {
                this.FlexionEsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConexionLematizador.IServicioLematizacion")]
    public interface IServicioLematizacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/EsVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/EsVerboResponse")]
        System.Threading.Tasks.Task<bool> EsVerboAsync(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/Reconocer", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.Reconocimiento>> ReconocerAsync(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerFlexible", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerFlexibleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.Reconocimiento>> ReconocerFlexibleAsync(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerVerboResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.Reconocimiento>> ReconocerVerboAsync(string verbo, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCanonica", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCanonicaResponse")]
        System.Threading.Tasks.Task<ConexionLematizador.InfoCanonica> ConsultaCanonicaAsync(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPalabra", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPalabraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoPalabra>> ConsultaPalabraAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexionador", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionadorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoFlexionador>> ConsultaFlexionadorAsync(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaVerboResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoVerbo>> ConsultaVerboAsync(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrimitiva", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrimitivaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoPrimitiva>> ConsultaPrimitivaAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoPrefijo>> ConsultaPrefijoAsync(string prefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCod", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCodResponse")]
        System.Threading.Tasks.Task<ConexionLematizador.InfoPrefijo> ConsultaPrefijoCodAsync(int idPrefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexion", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionResponse")]
        System.Threading.Tasks.Task<ConexionLematizador.InfoFlexion> ConsultaFlexionAsync(int idFlexion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServicioLematizacionChannel : ConexionLematizador.IServicioLematizacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServicioLematizacionClient : System.ServiceModel.ClientBase<ConexionLematizador.IServicioLematizacion>, ConexionLematizador.IServicioLematizacion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioLematizacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioLematizacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioLematizacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioLematizacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioLematizacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioLematizacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioLematizacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioLematizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> EsVerboAsync(string verbo)
        {
            return base.Channel.EsVerboAsync(verbo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.Reconocimiento>> ReconocerAsync(string palabra, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerAsync(palabra, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.Reconocimiento>> ReconocerFlexibleAsync(string palabra, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerFlexibleAsync(palabra, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.Reconocimiento>> ReconocerVerboAsync(string verbo, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerVerboAsync(verbo, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<ConexionLematizador.InfoCanonica> ConsultaCanonicaAsync(int idFormaCanonica)
        {
            return base.Channel.ConsultaCanonicaAsync(idFormaCanonica);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoPalabra>> ConsultaPalabraAsync(string palabra)
        {
            return base.Channel.ConsultaPalabraAsync(palabra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoFlexionador>> ConsultaFlexionadorAsync(int idFormaCanonica)
        {
            return base.Channel.ConsultaFlexionadorAsync(idFormaCanonica);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoVerbo>> ConsultaVerboAsync(string verbo)
        {
            return base.Channel.ConsultaVerboAsync(verbo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoPrimitiva>> ConsultaPrimitivaAsync(string palabra)
        {
            return base.Channel.ConsultaPrimitivaAsync(palabra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConexionLematizador.InfoPrefijo>> ConsultaPrefijoAsync(string prefijo)
        {
            return base.Channel.ConsultaPrefijoAsync(prefijo);
        }
        
        public System.Threading.Tasks.Task<ConexionLematizador.InfoPrefijo> ConsultaPrefijoCodAsync(int idPrefijo)
        {
            return base.Channel.ConsultaPrefijoCodAsync(idPrefijo);
        }
        
        public System.Threading.Tasks.Task<ConexionLematizador.InfoFlexion> ConsultaFlexionAsync(int idFlexion)
        {
            return base.Channel.ConsultaFlexionAsync(idFlexion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioLematizacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IServicioLematizacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioLematizacion))
            {
                return new System.ServiceModel.EndpointAddress("http://appstip.iatext.ulpgc.es/ServicioLematizacionWCF/ServicioLematizacion.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IServicioLematizacion))
            {
                return new System.ServiceModel.EndpointAddress("https://appstip.iatext.ulpgc.es/ServicioLematizacionWCF/ServicioLematizacion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioLematizacion,
            
            BasicHttpsBinding_IServicioLematizacion,
        }
    }
}
