//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioLematizador
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tulengua.es/", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.Generic.List<object>
    {
    }

    public class anyType : System.Object { }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tulengua.es/", ConfigurationName="ServicioLematizador.LematizadorSoap")]
    public interface LematizadorSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tulengua.es/ReconocerFlexible", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioLematizador.ReconocerFlexibleResponse> ReconocerFlexibleAsync(ServicioLematizador.ReconocerFlexibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tulengua.es/Reconocer", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioLematizador.ReconocerResponse> ReconocerAsync(ServicioLematizador.ReconocerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tulengua.es/Consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioLematizador.ConsultaResponse> ConsultaAsync(ServicioLematizador.ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tulengua.es/EsVerbo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioLematizador.EsVerboResponse> EsVerboAsync(ServicioLematizador.EsVerboRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tulengua.es/ReconocerVerbo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioLematizador.ReconocerVerboResponse> ReconocerVerboAsync(ServicioLematizador.ReconocerVerboRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReconocerFlexibleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReconocerFlexible", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ReconocerFlexibleRequestBody Body;
        
        public ReconocerFlexibleRequest()
        {
        }
        
        public ReconocerFlexibleRequest(ServicioLematizador.ReconocerFlexibleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ReconocerFlexibleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool multiPref;
        
        public ReconocerFlexibleRequestBody()
        {
        }
        
        public ReconocerFlexibleRequestBody(string key, string idioma, bool multiPref)
        {
            this.key = key;
            this.idioma = idioma;
            this.multiPref = multiPref;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReconocerFlexibleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReconocerFlexibleResponse", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ReconocerFlexibleResponseBody Body;
        
        public ReconocerFlexibleResponse()
        {
        }
        
        public ReconocerFlexibleResponse(ServicioLematizador.ReconocerFlexibleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ReconocerFlexibleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioLematizador.ArrayOfAnyType ReconocerFlexibleResult;
        
        public ReconocerFlexibleResponseBody()
        {
        }
        
        public ReconocerFlexibleResponseBody(ServicioLematizador.ArrayOfAnyType ReconocerFlexibleResult)
        {
            this.ReconocerFlexibleResult = ReconocerFlexibleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReconocerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reconocer", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ReconocerRequestBody Body;
        
        public ReconocerRequest()
        {
        }
        
        public ReconocerRequest(ServicioLematizador.ReconocerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ReconocerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool multiPref;
        
        public ReconocerRequestBody()
        {
        }
        
        public ReconocerRequestBody(string key, string idioma, bool multiPref)
        {
            this.key = key;
            this.idioma = idioma;
            this.multiPref = multiPref;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReconocerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReconocerResponse", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ReconocerResponseBody Body;
        
        public ReconocerResponse()
        {
        }
        
        public ReconocerResponse(ServicioLematizador.ReconocerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ReconocerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioLematizador.ArrayOfAnyType ReconocerResult;
        
        public ReconocerResponseBody()
        {
        }
        
        public ReconocerResponseBody(ServicioLematizador.ArrayOfAnyType ReconocerResult)
        {
            this.ReconocerResult = ReconocerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ConsultaRequestBody Body;
        
        public ConsultaRequest()
        {
        }
        
        public ConsultaRequest(ServicioLematizador.ConsultaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ConsultaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fd;
        
        public ConsultaRequestBody()
        {
        }
        
        public ConsultaRequestBody(string key, string idioma, string fd)
        {
            this.key = key;
            this.idioma = idioma;
            this.fd = fd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaResponse", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ConsultaResponseBody Body;
        
        public ConsultaResponse()
        {
        }
        
        public ConsultaResponse(ServicioLematizador.ConsultaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ConsultaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioLematizador.ArrayOfAnyType ConsultaResult;
        
        public ConsultaResponseBody()
        {
        }
        
        public ConsultaResponseBody(ServicioLematizador.ArrayOfAnyType ConsultaResult)
        {
            this.ConsultaResult = ConsultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsVerboRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsVerbo", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.EsVerboRequestBody Body;
        
        public EsVerboRequest()
        {
        }
        
        public EsVerboRequest(ServicioLematizador.EsVerboRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class EsVerboRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public EsVerboRequestBody()
        {
        }
        
        public EsVerboRequestBody(string word)
        {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsVerboResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsVerboResponse", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.EsVerboResponseBody Body;
        
        public EsVerboResponse()
        {
        }
        
        public EsVerboResponse(ServicioLematizador.EsVerboResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class EsVerboResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EsVerboResult;
        
        public EsVerboResponseBody()
        {
        }
        
        public EsVerboResponseBody(bool EsVerboResult)
        {
            this.EsVerboResult = EsVerboResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReconocerVerboRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReconocerVerbo", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ReconocerVerboRequestBody Body;
        
        public ReconocerVerboRequest()
        {
        }
        
        public ReconocerVerboRequest(ServicioLematizador.ReconocerVerboRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ReconocerVerboRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool multiPref;
        
        public ReconocerVerboRequestBody()
        {
        }
        
        public ReconocerVerboRequestBody(string key, string idioma, bool multiPref)
        {
            this.key = key;
            this.idioma = idioma;
            this.multiPref = multiPref;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReconocerVerboResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReconocerVerboResponse", Namespace="http://tulengua.es/", Order=0)]
        public ServicioLematizador.ReconocerVerboResponseBody Body;
        
        public ReconocerVerboResponse()
        {
        }
        
        public ReconocerVerboResponse(ServicioLematizador.ReconocerVerboResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tulengua.es/")]
    public partial class ReconocerVerboResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioLematizador.ArrayOfAnyType ReconocerVerboResult;
        
        public ReconocerVerboResponseBody()
        {
        }
        
        public ReconocerVerboResponseBody(ServicioLematizador.ArrayOfAnyType ReconocerVerboResult)
        {
            this.ReconocerVerboResult = ReconocerVerboResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface LematizadorSoapChannel : ServicioLematizador.LematizadorSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class LematizadorSoapClient : System.ServiceModel.ClientBase<ServicioLematizador.LematizadorSoap>, ServicioLematizador.LematizadorSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LematizadorSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LematizadorSoapClient.GetBindingForEndpoint(endpointConfiguration), LematizadorSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LematizadorSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LematizadorSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LematizadorSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LematizadorSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LematizadorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public LematizadorSoapClient()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioLematizador.ReconocerFlexibleResponse> ServicioLematizador.LematizadorSoap.ReconocerFlexibleAsync(ServicioLematizador.ReconocerFlexibleRequest request)
        {
            return base.Channel.ReconocerFlexibleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizador.ReconocerFlexibleResponse> ReconocerFlexibleAsync(string key, string idioma, bool multiPref)
        {
            ServicioLematizador.ReconocerFlexibleRequest inValue = new ServicioLematizador.ReconocerFlexibleRequest();
            inValue.Body = new ServicioLematizador.ReconocerFlexibleRequestBody();
            inValue.Body.key = key;
            inValue.Body.idioma = idioma;
            inValue.Body.multiPref = multiPref;
            return ((ServicioLematizador.LematizadorSoap)(this)).ReconocerFlexibleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioLematizador.ReconocerResponse> ServicioLematizador.LematizadorSoap.ReconocerAsync(ServicioLematizador.ReconocerRequest request)
        {
            return base.Channel.ReconocerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizador.ReconocerResponse> ReconocerAsync(string key, string idioma, bool multiPref)
        {
            ServicioLematizador.ReconocerRequest inValue = new ServicioLematizador.ReconocerRequest();
            inValue.Body = new ServicioLematizador.ReconocerRequestBody();
            inValue.Body.key = key;
            inValue.Body.idioma = idioma;
            inValue.Body.multiPref = multiPref;
            return ((ServicioLematizador.LematizadorSoap)(this)).ReconocerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioLematizador.ConsultaResponse> ServicioLematizador.LematizadorSoap.ConsultaAsync(ServicioLematizador.ConsultaRequest request)
        {
            return base.Channel.ConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizador.ConsultaResponse> ConsultaAsync(string key, string idioma, string fd)
        {
            ServicioLematizador.ConsultaRequest inValue = new ServicioLematizador.ConsultaRequest();
            inValue.Body = new ServicioLematizador.ConsultaRequestBody();
            inValue.Body.key = key;
            inValue.Body.idioma = idioma;
            inValue.Body.fd = fd;
            return ((ServicioLematizador.LematizadorSoap)(this)).ConsultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioLematizador.EsVerboResponse> ServicioLematizador.LematizadorSoap.EsVerboAsync(ServicioLematizador.EsVerboRequest request)
        {
            return base.Channel.EsVerboAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizador.EsVerboResponse> EsVerboAsync(string word)
        {
            ServicioLematizador.EsVerboRequest inValue = new ServicioLematizador.EsVerboRequest();
            inValue.Body = new ServicioLematizador.EsVerboRequestBody();
            inValue.Body.word = word;
            return ((ServicioLematizador.LematizadorSoap)(this)).EsVerboAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioLematizador.ReconocerVerboResponse> ServicioLematizador.LematizadorSoap.ReconocerVerboAsync(ServicioLematizador.ReconocerVerboRequest request)
        {
            return base.Channel.ReconocerVerboAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizador.ReconocerVerboResponse> ReconocerVerboAsync(string key, string idioma, bool multiPref)
        {
            ServicioLematizador.ReconocerVerboRequest inValue = new ServicioLematizador.ReconocerVerboRequest();
            inValue.Body = new ServicioLematizador.ReconocerVerboRequestBody();
            inValue.Body.key = key;
            inValue.Body.idioma = idioma;
            inValue.Body.multiPref = multiPref;
            return ((ServicioLematizador.LematizadorSoap)(this)).ReconocerVerboAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LematizadorSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LematizadorSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LematizadorSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://appstip.iatext.ulpgc.es/lematizador/Lematizador.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LematizadorSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://appstip.iatext.ulpgc.es/lematizador/Lematizador.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LematizadorSoap,
            
            LematizadorSoap12,
        }
    }
}
